/* The following code was generated by JFlex 1.4.3 on 2/4/22 1:50 PM */

/* JFlex example: partial Java language lexer specification */

package com.deimos.compilador.services.analysis;
import com.deimos.compilador.services.ErrorHandlerService;
import com.deimos.compilador.model.errors.ErrorType;
import com.deimos.compilador.model.errors.CompilationError;
import java.util.List;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/4/22 1:50 PM from the specification file
 * <tt>C:/Users/arcin/Documents/NetBeansProjects/Compilador/src/main/java/com/deimos/compilador/services/analysis/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  4,  0,  5,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    39, 35, 25,  0,  0, 33, 38,  0, 29, 30,  7, 31,  0, 32,  0,  6, 
     8,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 26, 37, 34, 36,  0, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 41,  0,  0,  0, 
     0, 11, 22,  9,  1, 16, 18, 24, 21, 13,  1, 23, 10,  1, 14, 19, 
     1,  1, 17, 12, 15,  1,  1, 20,  1,  1,  1, 27, 40, 28,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\3\4\1\5\1\6\1\3"+
    "\10\2\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\1\1\21\1\22\2\1\1\23"+
    "\1\1\1\24\1\25\2\0\1\4\1\0\1\26\1\27"+
    "\1\30\5\2\1\31\6\2\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\0\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\2\0\4\2\1\51\3\2"+
    "\1\52\3\2\1\53\1\0\1\4\3\2\1\54\1\2"+
    "\1\55\4\2\1\56\3\2\1\57\1\60\1\61\2\2"+
    "\1\62\3\2\1\63\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\124"+
    "\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c"+
    "\0\u0276\0\u02a0\0\u02ca\0\124\0\124\0\124\0\124\0\124"+
    "\0\124\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03f0"+
    "\0\u041a\0\u0444\0\u046e\0\374\0\124\0\u0498\0\374\0\u04c2"+
    "\0\u04ec\0\u0516\0\124\0\124\0\u017a\0\u0540\0\u056a\0\u0594"+
    "\0\u05be\0\u05e8\0\176\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba"+
    "\0\u06e4\0\124\0\124\0\124\0\124\0\124\0\124\0\124"+
    "\0\124\0\124\0\u070e\0\124\0\124\0\124\0\124\0\124"+
    "\0\124\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\176"+
    "\0\u0834\0\u085e\0\u0888\0\176\0\u08b2\0\u08dc\0\u0906\0\124"+
    "\0\u0930\0\u0738\0\u095a\0\u0984\0\u09ae\0\176\0\u09d8\0\176"+
    "\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\176\0\u0aaa\0\u0ad4\0\u0afe"+
    "\0\176\0\176\0\176\0\u0b28\0\u0b52\0\176\0\u0b7c\0\u0ba6"+
    "\0\u0bd0\0\176\0\176\0\176";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\4\1\15\1\16\1\17\2\4\1\20"+
    "\1\4\1\21\1\4\1\22\1\4\1\23\2\4\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\10\1\42\1\3"+
    "\3\43\1\3\1\44\24\43\1\45\17\43\1\46\53\0"+
    "\2\4\5\0\21\4\23\0\1\5\5\0\1\5\45\0"+
    "\1\10\45\0\4\47\1\0\24\47\1\50\20\47\6\0"+
    "\1\51\1\52\32\0\1\53\51\0\1\54\11\0\1\55"+
    "\5\0\1\55\42\0\2\4\5\0\2\4\1\56\16\4"+
    "\22\0\2\4\5\0\16\4\1\57\2\4\22\0\2\4"+
    "\5\0\7\4\1\60\11\4\22\0\2\4\5\0\6\4"+
    "\1\61\1\62\2\4\1\63\6\4\22\0\2\4\5\0"+
    "\2\4\1\64\16\4\22\0\2\4\5\0\2\4\1\65"+
    "\10\4\1\66\5\4\22\0\2\4\5\0\15\4\1\67"+
    "\3\4\22\0\2\4\5\0\11\4\1\70\1\4\1\71"+
    "\5\4\60\0\1\72\2\0\1\73\47\0\1\74\1\0"+
    "\1\75\51\0\1\76\51\0\1\77\51\0\1\100\51\0"+
    "\1\101\51\0\1\102\55\0\1\103\53\0\1\104\1\0"+
    "\3\43\2\0\24\43\1\0\17\43\17\0\1\105\1\106"+
    "\1\0\1\107\7\0\1\110\20\0\4\50\1\111\24\50"+
    "\1\0\20\50\3\51\1\6\1\10\45\51\7\112\1\113"+
    "\42\112\1\0\2\4\5\0\3\4\1\114\15\4\22\0"+
    "\2\4\5\0\4\4\1\115\14\4\22\0\2\4\5\0"+
    "\11\4\1\116\7\4\22\0\2\4\5\0\5\4\1\117"+
    "\1\4\1\120\11\4\22\0\2\4\5\0\10\4\1\121"+
    "\10\4\22\0\2\4\5\0\4\4\1\122\14\4\22\0"+
    "\2\4\5\0\13\4\1\123\5\4\22\0\2\4\5\0"+
    "\11\4\1\124\7\4\22\0\2\4\5\0\5\4\1\125"+
    "\13\4\22\0\2\4\5\0\10\4\1\126\10\4\22\0"+
    "\2\4\5\0\13\4\1\127\5\4\70\0\1\130\2\0"+
    "\7\112\1\131\50\112\1\132\1\131\42\112\1\0\2\4"+
    "\5\0\4\4\1\133\14\4\22\0\2\4\5\0\7\4"+
    "\1\134\11\4\22\0\2\4\5\0\5\4\1\135\13\4"+
    "\22\0\2\4\5\0\7\4\1\136\11\4\22\0\2\4"+
    "\5\0\11\4\1\137\7\4\22\0\2\4\5\0\10\4"+
    "\1\140\10\4\22\0\2\4\5\0\3\4\1\141\15\4"+
    "\22\0\2\4\5\0\2\4\1\142\16\4\22\0\2\4"+
    "\5\0\3\4\1\143\15\4\22\0\2\4\5\0\2\4"+
    "\1\144\16\4\21\0\6\112\1\10\1\131\42\112\1\0"+
    "\2\4\5\0\4\4\1\145\14\4\22\0\2\4\5\0"+
    "\11\4\1\146\7\4\22\0\2\4\5\0\6\4\1\147"+
    "\12\4\22\0\2\4\5\0\3\4\1\150\15\4\22\0"+
    "\2\4\5\0\7\4\1\151\11\4\22\0\2\4\5\0"+
    "\10\4\1\152\10\4\22\0\2\4\5\0\17\4\1\153"+
    "\1\4\22\0\2\4\5\0\10\4\1\154\10\4\22\0"+
    "\2\4\5\0\3\4\1\155\15\4\22\0\2\4\5\0"+
    "\20\4\1\156\22\0\2\4\5\0\7\4\1\157\11\4"+
    "\22\0\2\4\5\0\3\4\1\160\15\4\22\0\2\4"+
    "\5\0\1\4\1\161\17\4\22\0\2\4\5\0\10\4"+
    "\1\162\10\4\22\0\2\4\5\0\6\4\1\163\12\4"+
    "\22\0\2\4\5\0\7\4\1\164\11\4\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3066];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\1\11\13\1\6\11\13\1\1\11"+
    "\1\1\2\0\1\1\1\0\2\11\15\1\11\11\1\0"+
    "\6\11\2\0\14\1\1\11\1\0\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }

    private void addLexicalError(String id, int line, String message, String content){
       List<CompilationError> errors = ErrorHandlerService.compilationErrors.getErrors();
       CompilationError lexicalError = new CompilationError(id, message, content, ErrorType.LEXICAL, line);
       errors.add(lexicalError); 
    }

    private static final String INVALID_CHARACTER_ERROR_CODE = "001";
    private static final String INVALID_NUMBER_ERROR_CODE = "002";
    private static final String UNCLOSED_STRING_ERROR_CODE = "014";

    private static final String UNCLOSED_STRING_MESSAGE = "Unclosed string literal";
    private static final String INVALID_CHARACTER_MESSAGE = "Invalid character";
    private static final String INVALID_NUMBER_MESSAGE = "Invalid number";


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { /* ignore */
          }
        case 54: break;
        case 46: 
          { return symbol(sym.CLASS);
          }
        case 55: break;
        case 23: 
          { return symbol(sym.ASSIGNMENT_MULTIPLICATION);
          }
        case 56: break;
        case 24: 
          { addLexicalError(INVALID_NUMBER_ERROR_CODE, yyline+1, INVALID_NUMBER_MESSAGE, yytext()); return symbol(sym.INVALID_NUMBER);
          }
        case 57: break;
        case 11: 
          { return symbol(sym.LPAR);
          }
        case 58: break;
        case 22: 
          { return symbol(sym.ASSIGNMENT_DIVISION);
          }
        case 59: break;
        case 37: 
          { string.append('\t');
          }
        case 60: break;
        case 44: 
          { return symbol(sym.INIT);
          }
        case 61: break;
        case 34: 
          { return symbol(sym.LESS_THAN_OR_EQUAL_TO);
          }
        case 62: break;
        case 51: 
          { return symbol(sym.ITERATE);
          }
        case 63: break;
        case 7: 
          { string.setLength(0); yybegin(STRING);
          }
        case 64: break;
        case 41: 
          { return symbol(sym.INT);
          }
        case 65: break;
        case 12: 
          { return symbol(sym.RPAR);
          }
        case 66: break;
        case 9: 
          { return symbol(sym.LBRACKET);
          }
        case 67: break;
        case 43: 
          { return symbol(sym.AND);
          }
        case 68: break;
        case 1: 
          { addLexicalError(INVALID_CHARACTER_ERROR_CODE, yyline+1, INVALID_CHARACTER_MESSAGE, yytext()); return symbol(sym.ERROR);
          }
        case 69: break;
        case 17: 
          { return symbol(sym.GREATER_THAN);
          }
        case 70: break;
        case 40: 
          { addLexicalError(INVALID_CHARACTER_ERROR_CODE, yyline+1, UNCLOSED_STRING_MESSAGE, yytext()); return symbol(sym.ERROR);
          }
        case 71: break;
        case 21: 
          { string.append('\\');
          }
        case 72: break;
        case 31: 
          { return symbol(sym.EQUAL_TO);
          }
        case 73: break;
        case 32: 
          { return symbol(sym.NOT_EQUAL);
          }
        case 74: break;
        case 38: 
          { string.append('\r');
          }
        case 75: break;
        case 28: 
          { return symbol(sym.DECREMENT);
          }
        case 76: break;
        case 3: 
          { return symbol(sym.INTEGER_LITERAL, new Integer(yytext()));
          }
        case 77: break;
        case 26: 
          { return symbol(sym.INCREMENT);
          }
        case 78: break;
        case 2: 
          { return symbol(sym.IDENTIFIER, yytext());
          }
        case 79: break;
        case 27: 
          { return symbol(sym.ASSIGNMENT_ADDITION);
          }
        case 80: break;
        case 10: 
          { return symbol(sym.RBRACKET);
          }
        case 81: break;
        case 45: 
          { return symbol(sym.ELSE);
          }
        case 82: break;
        case 39: 
          { string.append('\"');
          }
        case 83: break;
        case 5: 
          { return symbol(sym.DIVISION);
          }
        case 84: break;
        case 48: 
          { return symbol(sym.WHILE);
          }
        case 85: break;
        case 49: 
          { return symbol(sym.BREAK);
          }
        case 86: break;
        case 25: 
          { return symbol(sym.IF);
          }
        case 87: break;
        case 35: 
          { return symbol(sym.OR);
          }
        case 88: break;
        case 33: 
          { return symbol(sym.GREATHER_THAN_OR_EQUAL_TO);
          }
        case 89: break;
        case 6: 
          { return symbol(sym.MULTIPLICATION);
          }
        case 90: break;
        case 30: 
          { return symbol(sym.ASSIGNMENT_MODULUS);
          }
        case 91: break;
        case 42: 
          { return symbol(sym.FOR);
          }
        case 92: break;
        case 47: 
          { return symbol(sym.FLOAT);
          }
        case 93: break;
        case 36: 
          { string.append('\n');
          }
        case 94: break;
        case 29: 
          { return symbol(sym.ASSIGNMENT_SUBTRACTION);
          }
        case 95: break;
        case 8: 
          { return symbol(sym.SEMI);
          }
        case 96: break;
        case 16: 
          { return symbol(sym.ASSIGNMENT);
          }
        case 97: break;
        case 53: 
          { return symbol(sym.ABSTRACT);
          }
        case 98: break;
        case 14: 
          { return symbol(sym.SUBTRACTION);
          }
        case 99: break;
        case 52: 
          { return symbol(sym.BOOLEAN);
          }
        case 100: break;
        case 15: 
          { return symbol(sym.MODULUS);
          }
        case 101: break;
        case 13: 
          { return symbol(sym.ADDITION);
          }
        case 102: break;
        case 20: 
          { yybegin(YYINITIAL);
                                   return symbol(sym.STRING_LITERAL,
                                   string.toString());
          }
        case 103: break;
        case 50: 
          { return symbol(sym.STRING);
          }
        case 104: break;
        case 18: 
          { return symbol(sym.LESS_THAN);
          }
        case 105: break;
        case 19: 
          { string.append( yytext() );
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
