
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 07 19:26:53 MST 2022
//----------------------------------------------------

package com.deimos.compilador.services.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 26;
  public static final int LBRACKET = 49;
  public static final int INCREMENT = 32;
  public static final int PIN = 24;
  public static final int ASSIGNMENT = 34;
  public static final int NOT_EQUAL = 41;
  public static final int SEMI = 48;
  public static final int INT = 12;
  public static final int INIT = 6;
  public static final int FOR = 10;
  public static final int DECREMENT = 33;
  public static final int GREATER_THAN = 42;
  public static final int A_READ = 19;
  public static final int AND = 46;
  public static final int RPAR = 52;
  public static final int OR = 47;
  public static final int SUBTRACTION = 28;
  public static final int IF = 8;
  public static final int D_WRITE = 22;
  public static final int A_WRITE = 20;
  public static final int WAIT = 16;
  public static final int ABSTRACT = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RBRACKET = 50;
  public static final int error = 1;
  public static final int PROGRAM = 5;
  public static final int COMA = 54;
  public static final int MODE = 18;
  public static final int ASSIGNMENT_MULTIPLICATION = 37;
  public static final int START = 15;
  public static final int BREAK = 4;
  public static final int EQUAL_TO = 40;
  public static final int ERROR = 55;
  public static final int ASSIGNMENT_MODULUS = 39;
  public static final int ITERATE = 7;
  public static final int INVALID_NUMBER = 53;
  public static final int ASSIGNMENT_ADDITION = 35;
  public static final int ELSE = 9;
  public static final int GREATHER_THAN_OR_EQUAL_TO = 44;
  public static final int WHILE = 11;
  public static final int ADDITION = 27;
  public static final int FLOAT = 14;
  public static final int ASSIGNMENT_DIVISION = 38;
  public static final int MODULUS = 31;
  public static final int D_READ = 21;
  public static final int LPAR = 51;
  public static final int STRING = 13;
  public static final int DIVISION = 30;
  public static final int LESS_THAN = 43;
  public static final int LESS_THAN_OR_EQUAL_TO = 45;
  public static final int ASSIGNMENT_SUBTRACTION = 36;
  public static final int MULTIPLICATION = 29;
  public static final int PRINT = 17;
  public static final int INTEGER_LITERAL = 25;
  public static final int IDENTIFIER = 23;
}

