
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 04 13:50:41 MST 2022
//----------------------------------------------------

package com.deimos.compilador.services.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 17;
  public static final int LBRACKET = 40;
  public static final int INCREMENT = 23;
  public static final int ASSIGNMENT = 25;
  public static final int NOT_EQUAL = 32;
  public static final int SEMI = 39;
  public static final int INT = 12;
  public static final int INIT = 6;
  public static final int FOR = 10;
  public static final int DECREMENT = 24;
  public static final int GREATER_THAN = 33;
  public static final int AND = 37;
  public static final int RPAR = 43;
  public static final int OR = 38;
  public static final int CLASS = 5;
  public static final int SUBTRACTION = 19;
  public static final int IF = 8;
  public static final int ABSTRACT = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RBRACKET = 41;
  public static final int error = 1;
  public static final int ASSIGNMENT_MULTIPLICATION = 28;
  public static final int BREAK = 4;
  public static final int EQUAL_TO = 31;
  public static final int ERROR = 45;
  public static final int ASSIGNMENT_MODULUS = 30;
  public static final int ITERATE = 7;
  public static final int INVALID_NUMBER = 44;
  public static final int ASSIGNMENT_ADDITION = 26;
  public static final int ELSE = 9;
  public static final int GREATHER_THAN_OR_EQUAL_TO = 35;
  public static final int WHILE = 11;
  public static final int ADDITION = 18;
  public static final int FLOAT = 14;
  public static final int ASSIGNMENT_DIVISION = 29;
  public static final int MODULUS = 22;
  public static final int LPAR = 42;
  public static final int STRING = 13;
  public static final int DIVISION = 21;
  public static final int LESS_THAN = 34;
  public static final int LESS_THAN_OR_EQUAL_TO = 36;
  public static final int ASSIGNMENT_SUBTRACTION = 27;
  public static final int MULTIPLICATION = 20;
  public static final int INTEGER_LITERAL = 16;
  public static final int IDENTIFIER = 15;
}

