
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 06 13:24:49 MST 2022
//----------------------------------------------------

package com.deimos.compilador.services.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 22;
  public static final int LBRACKET = 45;
  public static final int INCREMENT = 28;
  public static final int PIN = 20;
  public static final int ASSIGNMENT = 30;
  public static final int NOT_EQUAL = 37;
  public static final int SEMI = 44;
  public static final int INT = 12;
  public static final int INIT = 6;
  public static final int FOR = 10;
  public static final int DECREMENT = 29;
  public static final int GREATER_THAN = 38;
  public static final int AND = 42;
  public static final int RPAR = 48;
  public static final int OR = 43;
  public static final int SUBTRACTION = 24;
  public static final int IF = 8;
  public static final int WAIT = 16;
  public static final int ABSTRACT = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RBRACKET = 46;
  public static final int error = 1;
  public static final int PROGRAM = 5;
  public static final int ASSIGNMENT_MULTIPLICATION = 33;
  public static final int START = 15;
  public static final int BREAK = 4;
  public static final int EQUAL_TO = 36;
  public static final int ERROR = 50;
  public static final int ASSIGNMENT_MODULUS = 35;
  public static final int ITERATE = 7;
  public static final int INVALID_NUMBER = 49;
  public static final int ASSIGNMENT_ADDITION = 31;
  public static final int ELSE = 9;
  public static final int GREATHER_THAN_OR_EQUAL_TO = 40;
  public static final int READ = 17;
  public static final int WHILE = 11;
  public static final int ADDITION = 23;
  public static final int FLOAT = 14;
  public static final int ASSIGNMENT_DIVISION = 34;
  public static final int MODULUS = 27;
  public static final int LPAR = 47;
  public static final int STRING = 13;
  public static final int DIVISION = 26;
  public static final int LESS_THAN = 39;
  public static final int LESS_THAN_OR_EQUAL_TO = 41;
  public static final int ASSIGNMENT_SUBTRACTION = 32;
  public static final int MULTIPLICATION = 25;
  public static final int PRINT = 18;
  public static final int INTEGER_LITERAL = 21;
  public static final int IDENTIFIER = 19;
}

